version: '3'
services:
  denbackend:
    build:
      context: ./backend
    environment:
      - "STORAGE=mysql"
      - "MYSQL_HOST=dendb"
      - "MYSQL_USER=${sqlUsr}"
      - "MYSQL_PWD=${sqlPass}"
      - "MYSQL_DB=${sqlDb}"
    networks:
      - proxy
      - backend_db
    labels:
      - "traefik.http.routers.denbackend.rule=Host(`h4kim.tech`) && Path(`/api/{name:.*}`)"
      - "traefik.http.routers.denbackend.tls=true"
      - "traefik.http.routers.denbackend.tls.certresolver=letsencrypt"  
      - "traefik.docker.network=traefik"

    

  denfrontend:
    image: nginx:1.22
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - proxy
    labels:
      - "traefik.http.routers.de_frontend.rule=Host(`h4kim.tech`)"
      - "traefik.http.routers.de_frontend.tls=true"
      - "traefik.http.routers.de_frontend.tls.certresolver=letsencrypt"  
      - "traefik.docker.network=traefik"


  dendb:
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${sqlRootPass}"
      - "MYSQL_DATABASE=${sqlDb}"
      - "MYSQL_USER=${sqlUsr}"
      - "MYSQL_PASSWORD=${sqlPass}"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql:ro
    networks:
      - backend_db


volumes:
  db-data:

networks:
  proxy:
    external: true
    name: traefik
  backend_db:

